#!/bin/sh

set -e

short=$(git rev-parse --short HEAD)
full=$(git rev-parse HEAD)

cat > build.js <<EOF
(function () {
  var mark = document.getElementById('buildMark');
  mark.href = 'https://github.com/li9i/personal-board/commit/$full';
  mark.textContent = '$short';
})();
EOF
